
package aa;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prince Ali
 */
public class criminal extends javax.swing.JFrame {
    String selectedVlue;
    String Value;

    /**
     * Creates new form criminal
     */
    public criminal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ctable = new javax.swing.JTable();
        name = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        nationality = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        mainbtn = new javax.swing.JButton();
        Logoutbtn1 = new javax.swing.JButton();
        gender = new javax.swing.JLabel();
        nCombo = new javax.swing.JComboBox<>();
        gendercombo = new javax.swing.JComboBox<>();
        ofns = new javax.swing.JLabel();
        offComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criminal Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        Ctable.setBackground(new java.awt.Color(0, 153, 153));
        Ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.Name", "Gender", "Age", "Nationality", "Offense"
            }
        ));
        Ctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Ctable);

        name.setText("C.Name");

        age.setText("Age");

        nationality.setText("Ntionality");

        nametxt.setBackground(new java.awt.Color(0, 153, 153));

        agetxt.setBackground(new java.awt.Color(0, 153, 153));

        addbtn.setBackground(new java.awt.Color(0, 153, 153));
        addbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Register");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(0, 153, 153));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        mainbtn.setBackground(new java.awt.Color(0, 153, 153));
        mainbtn.setForeground(new java.awt.Color(255, 255, 255));
        mainbtn.setText("Main Menu");
        mainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbtnActionPerformed(evt);
            }
        });

        Logoutbtn1.setBackground(new java.awt.Color(0, 153, 153));
        Logoutbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbtn1.setText("Logout");
        Logoutbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logoutbtn1ActionPerformed(evt);
            }
        });

        gender.setText("Gender");

        nCombo.setBackground(new java.awt.Color(0, 153, 153));
        nCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pakistan", "Nigeria", "India", "America", "Dubai" }));
        nCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nComboActionPerformed(evt);
            }
        });

        gendercombo.setBackground(new java.awt.Color(0, 153, 153));
        gendercombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        ofns.setText("Type of offense");

        offComboBox.setBackground(new java.awt.Color(0, 153, 153));
        offComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucide Attempt", "Murder", "robbery", "burglary", "Kdnapping", "Domestic Voilence", "Computer crime", "Assault" }));
        offComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(mainbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Logoutbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(name)
                                    .addComponent(gender)
                                    .addComponent(age)
                                    .addComponent(nationality)
                                    .addComponent(ofns))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(gendercombo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(agetxt, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(nCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(offComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 172, Short.MAX_VALUE))
                                    .addComponent(nametxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(addbtn)
                                .addGap(12, 12, 12)
                                .addComponent(btnupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(name)
                                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(gendercombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gender))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(age)
                                    .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nationality))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ofns)
                                    .addComponent(offComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addbtn)
                            .addComponent(btnupdate)
                            .addComponent(jButton2))
                        .addGap(19, 19, 19)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainbtn)
                    .addComponent(Logoutbtn1))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        
        String name=nametxt.getText();
        
        String gender; 
       if(gendercombo.getSelectedItem().toString()== "Male"){
           gender = "Male";
       }else{
           gender = "Female";
       }
       String age = agetxt.getText();
         int ag=Integer.parseInt(age); 
        DefaultTableModel dt=(DefaultTableModel)Ctable.getModel();
        dt.addRow(new Object[]{nametxt.getText(),gender,agetxt.getText(),selectedVlue,Value});
        JOptionPane.showMessageDialog(this, "Record Addeded Successfully...");
        nametxt.setText("");
        agetxt.setText("");
    }//GEN-LAST:event_addbtnActionPerformed

    private void mainbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbtnActionPerformed
        // TODO add your handling code here:
        main m = new main();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_mainbtnActionPerformed

    private void Logoutbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logoutbtn1ActionPerformed
        // TODO add your handling code here:
        login lo = new login();
        this.hide();
        lo.setVisible(true);
    }//GEN-LAST:event_Logoutbtn1ActionPerformed

    private void nComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nComboActionPerformed
        // TODO add your handling code here:
      //  String Value;
         selectedVlue=nCombo.getSelectedItem().toString();
       // if (selectedVlue=="Pakistan")
       // {
       //     Value="Pakistan";
       // }
        
    }//GEN-LAST:event_nComboActionPerformed

    private void CtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CtableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Ctable.getModel();
       int selectRow = Ctable.getSelectedRow();
       nametxt.setText(model.getValueAt(selectRow, 0).toString());
       gender.setText(model.getValueAt(selectRow, 1).toString());
       agetxt.setText(model.getValueAt(selectRow, 2).toString());
      
    }//GEN-LAST:event_CtableMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
         String nLabel=nametxt.getText();
        String rLabel=agetxt.getText();
        //String aLabel=atxt.getText();
        DefaultTableModel dt=(DefaultTableModel)Ctable.getModel();
        int index=Ctable.getSelectedRow();
        dt.setValueAt(name, index, 0);
        dt.setValueAt(gender, index, 1);
        dt.setValueAt(age, index, 2);
         dt.setValueAt(nationality, index, 3);
          dt.setValueAt(ofns, index, 4);
        JOptionPane.showMessageDialog(this, "Updated");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt=(DefaultTableModel)Ctable.getModel();
        int index=Ctable.getSelectedRow();
        dt.removeRow(index);
            JOptionPane.showMessageDialog(this, "Record Delete");
            nametxt.setText("");
            gender.setText("");
            agetxt.setText("");
            
            addbtn.setEnabled(true);
            btnupdate.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void offComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offComboBoxActionPerformed
        // TODO add your handling code here:
        Value=offComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_offComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(criminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new criminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Ctable;
    private javax.swing.JButton Logoutbtn1;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agetxt;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel gender;
    private javax.swing.JComboBox<String> gendercombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainbtn;
    private javax.swing.JComboBox<String> nCombo;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel nationality;
    private javax.swing.JComboBox<String> offComboBox;
    private javax.swing.JLabel ofns;
    // End of variables declaration//GEN-END:variables
}
