
package aa;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Prince Ali
 */
public class Person1 extends javax.swing.JFrame {

    /**
     * Creates new form staff
     */
    public Person1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Message = new javax.swing.JPanel();
        nLabel = new javax.swing.JLabel();
        rLabel = new javax.swing.JLabel();
        cLabel = new javax.swing.JLabel();
        aLabel = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        ranktxt = new javax.swing.JTextField();
        cntxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addbtn = new javax.swing.JButton();
        detbtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        mainbtn = new javax.swing.JButton();
        Logoutbtn1 = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Message.setBackground(new java.awt.Color(0, 153, 153));
        Message.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Person Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        Message.setForeground(new java.awt.Color(255, 0, 0));

        nLabel.setText("Name");

        rLabel.setText("Rank");

        cLabel.setText("Contact No");

        aLabel.setText("Attendence");

        nametxt.setBackground(new java.awt.Color(0, 153, 153));
        nametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametxtActionPerformed(evt);
            }
        });

        ranktxt.setBackground(new java.awt.Color(0, 153, 153));

        cntxt.setBackground(new java.awt.Color(0, 153, 153));

        jTable1.setBackground(new java.awt.Color(0, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Rank", "Contact No", "Attendence"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addbtn.setBackground(new java.awt.Color(0, 153, 153));
        addbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Add");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        detbtn.setBackground(new java.awt.Color(0, 153, 153));
        detbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        detbtn.setForeground(new java.awt.Color(255, 255, 255));
        detbtn.setText("Delete");
        detbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detbtnActionPerformed(evt);
            }
        });

        editbtn.setBackground(new java.awt.Color(0, 153, 153));
        editbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editbtn.setForeground(new java.awt.Color(255, 255, 255));
        editbtn.setText("Update");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        mainbtn.setBackground(new java.awt.Color(0, 153, 153));
        mainbtn.setForeground(new java.awt.Color(255, 255, 255));
        mainbtn.setText("Main Menu");
        mainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbtnActionPerformed(evt);
            }
        });

        Logoutbtn1.setBackground(new java.awt.Color(0, 153, 153));
        Logoutbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbtn1.setText("Logout");
        Logoutbtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Logoutbtn1MouseClicked(evt);
            }
        });
        Logoutbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logoutbtn1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Present");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Absent");

        javax.swing.GroupLayout MessageLayout = new javax.swing.GroupLayout(Message);
        Message.setLayout(MessageLayout);
        MessageLayout.setHorizontalGroup(
            MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessageLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(mainbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logoutbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(MessageLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MessageLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(addbtn)
                        .addGap(26, 26, 26)
                        .addComponent(detbtn)
                        .addGap(18, 18, 18)
                        .addComponent(editbtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MessageLayout.createSequentialGroup()
                        .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MessageLayout.createSequentialGroup()
                                .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cLabel)
                                    .addComponent(aLabel)
                                    .addComponent(rLabel)
                                    .addComponent(nLabel))
                                .addGap(18, 18, 18)
                                .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cntxt, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                        .addComponent(ranktxt)
                                        .addComponent(nametxt))
                                    .addGroup(MessageLayout.createSequentialGroup()
                                        .addComponent(jRadioButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButton2)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MessageLayout.setVerticalGroup(
            MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MessageLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MessageLayout.createSequentialGroup()
                        .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ranktxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cntxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cLabel))
                        .addGap(10, 10, 10)
                        .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aLabel)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(detbtn)
                    .addComponent(editbtn))
                .addGap(18, 18, 18)
                .addGroup(MessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainbtn)
                    .addComponent(Logoutbtn1))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nametxtActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String nLabel=nametxt.getText();
        String rLabel=ranktxt.getText();
        String cLabel=cntxt.getText();
        String atten;
         if(jRadioButton1.isSelected())
      {
          atten="Present";
      }
      else
      {
          atten="Absent";
      }
        //String aLabel=atxt.getText();
        
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.addRow(new Object[]{nametxt.getText(),ranktxt.getText(),cntxt.getText(),atten});
        JOptionPane.showMessageDialog(this, "Record Addeded Successfully...");
            nametxt.setText("");
            ranktxt.setText("");
            cntxt.setText("");
           // atxt.setText("");
    }//GEN-LAST:event_addbtnActionPerformed

    private void mainbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbtnActionPerformed
        // TODO add your handling code here:
        main m = new main();       
     this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_mainbtnActionPerformed

    private void Logoutbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logoutbtn1ActionPerformed
        // TODO add your handling code here:
        login lo = new login();       
     this.hide();
        lo.setVisible(true);
    }//GEN-LAST:event_Logoutbtn1ActionPerformed

    private void detbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detbtnActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        int index=jTable1.getSelectedRow();
        dt.removeRow(index);
            JOptionPane.showMessageDialog(this, "Record Delete");
            nametxt.setText("");
            ranktxt.setText("");
            cntxt.setText("");
            
            addbtn.setEnabled(true);
            editbtn.setEnabled(false);
        
    }//GEN-LAST:event_detbtnActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
       int selectRow = jTable1.getSelectedRow();
       nametxt.setText(model.getValueAt(selectRow, 0).toString());
       ranktxt.setText(model.getValueAt(selectRow, 1).toString());
       cntxt.setText(model.getValueAt(selectRow, 2).toString());
       addbtn.setEnabled(false);
       editbtn.setEnabled(true);
    }//GEN-LAST:event_jTable1MouseClicked

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
           String nLabel=nametxt.getText();
        String rLabel=ranktxt.getText();
        String cLabel=cntxt.getText();
        //String aLabel=atxt.getText();
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        int index=jTable1.getSelectedRow();
        dt.setValueAt(nLabel, index, 0);
        dt.setValueAt(rLabel, index, 1);
        dt.setValueAt(cLabel, index, 2);
        JOptionPane.showMessageDialog(this, "Updated");
    }//GEN-LAST:event_editbtnActionPerformed

    private void Logoutbtn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Logoutbtn1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Logoutbtn1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Person1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Person1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Person1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Person1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Person1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logoutbtn1;
    private javax.swing.JPanel Message;
    private javax.swing.JLabel aLabel;
    private javax.swing.JButton addbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cLabel;
    private javax.swing.JTextField cntxt;
    private javax.swing.JButton detbtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton mainbtn;
    private javax.swing.JLabel nLabel;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel rLabel;
    private javax.swing.JTextField ranktxt;
    // End of variables declaration//GEN-END:variables
}
