/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aa;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Victim extends javax.swing.JFrame {
     String Value;
     String OF;
      String Jail;
    /**
     * Creates new form criminal
     */
    public Victim() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ptable = new javax.swing.JTable();
        name = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        agetxt = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        mainbtn = new javax.swing.JButton();
        Logoutbtn1 = new javax.swing.JButton();
        gender = new javax.swing.JLabel();
        Ncombo = new javax.swing.JComboBox<>();
        GCo = new javax.swing.JComboBox<>();
        off = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        cas = new javax.swing.JLabel();
        bail = new javax.swing.JLabel();
        jail = new javax.swing.JLabel();
        ctxt = new javax.swing.JTextField();
        bailCombo = new javax.swing.JComboBox<>();
        Jcombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Victim Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        ptable.setBackground(new java.awt.Color(0, 153, 153));
        ptable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "C.Name", "Gender", "Age", "Nationality", "Offense", "Case", "Status", "Jail"
            }
        ));
        ptable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ptableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ptable);

        name.setText("C.Name");

        age.setText("Age");

        city.setText("Ntionality");

        nametxt.setBackground(new java.awt.Color(0, 153, 153));

        agetxt.setBackground(new java.awt.Color(0, 153, 153));

        addbtn.setBackground(new java.awt.Color(0, 153, 153));
        addbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbtn.setForeground(new java.awt.Color(255, 255, 255));
        addbtn.setText("Register");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnupdate.setBackground(new java.awt.Color(0, 153, 153));
        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnupdate.setForeground(new java.awt.Color(255, 255, 255));
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        mainbtn.setBackground(new java.awt.Color(0, 153, 153));
        mainbtn.setForeground(new java.awt.Color(255, 255, 255));
        mainbtn.setText("Main Menu");
        mainbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainbtnActionPerformed(evt);
            }
        });

        Logoutbtn1.setBackground(new java.awt.Color(0, 153, 153));
        Logoutbtn1.setForeground(new java.awt.Color(255, 255, 255));
        Logoutbtn1.setText("Logout");
        Logoutbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logoutbtn1ActionPerformed(evt);
            }
        });

        gender.setText("Gender");

        Ncombo.setBackground(new java.awt.Color(0, 153, 153));
        Ncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pakistan", "Nigeria", "India", "America", "Dubai" }));
        Ncombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NcomboActionPerformed(evt);
            }
        });

        GCo.setBackground(new java.awt.Color(0, 153, 153));
        GCo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        off.setText("Type of offense");

        jComboBox3.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sucide Attempt", "Murder", "robbery", "burglary", "Kdnapping", "Domestic Voilence", "Computer crime", "Assault" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        cas.setText("Case\\File Num");

        bail.setText("Bail Status");

        jail.setText("Jail Term");

        ctxt.setBackground(new java.awt.Color(0, 153, 153));

        bailCombo.setBackground(new java.awt.Color(0, 153, 153));
        bailCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        Jcombo.setBackground(new java.awt.Color(0, 153, 153));
        Jcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-1 year", "1-2 years", "2-3 years", "3-4 years", "4-5 years", "1-5 years", " " }));
        Jcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Ncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(name)
                                        .addComponent(gender)
                                        .addComponent(age)
                                        .addComponent(city)
                                        .addComponent(off)
                                        .addComponent(bail)
                                        .addComponent(jail)
                                        .addComponent(cas, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jComboBox3, 0, 172, Short.MAX_VALUE)
                                        .addComponent(agetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(GCo, 0, 172, Short.MAX_VALUE)
                                        .addComponent(nametxt, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                                        .addComponent(ctxt)
                                        .addComponent(bailCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Jcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addbtn)
                                .addGap(18, 18, 18)
                                .addComponent(btnupdate)
                                .addGap(26, 26, 26)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(mainbtn)
                        .addGap(29, 29, 29)
                        .addComponent(Logoutbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name)
                            .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender)
                            .addComponent(GCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(age)
                            .addComponent(agetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ncombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(city))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(off)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cas))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bail)
                            .addComponent(bailCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jail)
                            .addComponent(Jcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addbtn)
                    .addComponent(btnupdate)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainbtn)
                    .addComponent(Logoutbtn1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        // TODO add your handling code here:
        String name=nametxt.getText();
        String gender; 
       if(GCo.getSelectedItem() == "Male"){
           gender = "Male";
       }else{
           gender = "Female";
       }
        String age = agetxt.getText();
         int ag=Integer.parseInt(age); 
         String Nati; 
       if(Ncombo.getSelectedItem() == "Pkistan"){
           Nati = "Pakistan";
       }else{
           Nati = "Nigeria";
       }
       String offen;
       String file = ctxt.getText();
         int ca=Integer.parseInt(file); 
       String status; 
       if(bailCombo.getSelectedItem() == "Yes"){
           status = "Yes";
       }else{
           status = "No";
       }
    
      DefaultTableModel dt=(DefaultTableModel)ptable.getModel();
        dt.addRow(new Object[]{nametxt.getText(),gender,agetxt.getText(),Value,OF,ctxt.getText(),status,Jail});
        JOptionPane.showMessageDialog(this, "Record Addeded Successfully...");
        nametxt.setText("");
        agetxt.setText("");
         ctxt.setText("");
     //   citytxt.setText("");
       // crimetxt.setText("");
    }//GEN-LAST:event_addbtnActionPerformed

    private void mainbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainbtnActionPerformed
        // TODO add your handling code here:
        main m = new main();
        this.hide();
        m.setVisible(true);
    }//GEN-LAST:event_mainbtnActionPerformed

    private void Logoutbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logoutbtn1ActionPerformed
        // TODO add your handling code here:
        login lo = new login();
        this.hide();
        lo.setVisible(true);
    }//GEN-LAST:event_Logoutbtn1ActionPerformed

    private void ptableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ptableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)ptable.getModel();
       int selectRow = ptable.getSelectedRow();
       nametxt.setText(model.getValueAt(selectRow, 0).toString());
       gender.setText(model.getValueAt(selectRow, 1).toString());
       agetxt.setText(model.getValueAt(selectRow, 2).toString());
       //Value.setText(model.getValueAt(selectRow, 3).toString());
       ctxt.setText(model.getValueAt(selectRow, 4).toString());
       ctxt.setText(model.getValueAt(selectRow, 5).toString());
       ctxt.setText(model.getValueAt(selectRow, 6).toString());
       ctxt.setText(model.getValueAt(selectRow, 7).toString());
       addbtn.setEnabled(false);
       btnupdate.setEnabled(true);
    }//GEN-LAST:event_ptableMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        String name=nametxt.getText();
        String age=agetxt.getText();
        String cas=ctxt.getText();
        //String aLabel=atxt.getText();
        DefaultTableModel dt=(DefaultTableModel)ptable.getModel();
        int index=ptable.getSelectedRow();
        dt.setValueAt(name, index, 0);
        dt.setValueAt(age, index, 1);
        dt.setValueAt(cas, index, 2);
        JOptionPane.showMessageDialog(this, "Updated");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dt=(DefaultTableModel)ptable.getModel();
        int index=ptable.getSelectedRow();
        dt.removeRow(index);
            JOptionPane.showMessageDialog(this, "Record Delete");
            nametxt.setText("");
            agetxt.setText("");
            ctxt.setText("");
            addbtn.setEnabled(true);
            btnupdate.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NcomboActionPerformed
        // TODO add your handling code here:
          Value=Ncombo.getSelectedItem().toString();
    }//GEN-LAST:event_NcomboActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        OF=jComboBox3.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void JcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboActionPerformed
        // TODO add your handling code here:
         Jail=Jcombo.getSelectedItem().toString();
    }//GEN-LAST:event_JcomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Victim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Victim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Victim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Victim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Victim().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GCo;
    private javax.swing.JComboBox<String> Jcombo;
    private javax.swing.JButton Logoutbtn1;
    private javax.swing.JComboBox<String> Ncombo;
    private javax.swing.JButton addbtn;
    private javax.swing.JLabel age;
    private javax.swing.JTextField agetxt;
    private javax.swing.JLabel bail;
    private javax.swing.JComboBox<String> bailCombo;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel cas;
    private javax.swing.JLabel city;
    private javax.swing.JTextField ctxt;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jail;
    private javax.swing.JButton mainbtn;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel off;
    private javax.swing.JTable ptable;
    // End of variables declaration//GEN-END:variables
}
